#!/usr/bin/env bun
// Morning Briefing Agent
// Run standalone: bun run src/briefing.ts
// Schedule via launchd for 6:00 AM PT daily

import { getMacroSnapshot, SERIES } from './clients/fred';
import { fetchGeoEvents } from './clients/gdelt';
import { getPerformanceMetrics, getDb } from './lib/db';
import { config } from './lib/config';
import type { BriefingData, GeoEvent, Dislocation } from './lib/types';
import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

async function generateBriefing(): Promise<string> {
  const today = new Date().toISOString().split('T')[0];
  console.log(`[briefing] Generating for ${today}...`);

  // Parallel data fetch
  const [macroSnapshot, geoEvents, track2Performance] = await Promise.all([
    getMacroSnapshot(),
    fetchGeoEvents(24),
    Promise.resolve(getPerformanceMetrics(undefined, 'volatility')),
  ]);

  // Build briefing markdown
  const lines: string[] = [
    `# Macro Sentinel Daily Briefing`,
    `**Date:** ${today} | **Mode:** ${config.mode}`,
    '',
    '---',
    '',
    '## Macro Indicators',
    '',
    '| Indicator | Value | Updated |',
    '|-----------|-------|---------|',
  ];

  for (const [id, label] of Object.entries(SERIES)) {
    const val = macroSnapshot[id];
    if (val) {
      lines.push(`| ${label} | ${val.value} | ${val.date} |`);
    } else {
      lines.push(`| ${label} | N/A | - |`);
    }
  }

  // Watchlist section
  lines.push('', '## Watchlist', '', '### Track 1: Macro Positions');
  lines.push('| Ticker | Sector | Status |');
  lines.push('|--------|--------|--------|');
  for (const ticker of config.watchlist.macro) {
    const sector = config.sectors[ticker] ?? 'other';
    lines.push(`| ${ticker} | ${sector} | monitoring |`);
  }

  // Geo events
  lines.push('', '## Geopolitical Events (Last 24h)', '');
  if (geoEvents.length === 0) {
    lines.push('*No significant events detected.*');
  } else {
    const highSeverity = geoEvents.filter(e => e.severity >= 3);
    const lowSeverity = geoEvents.filter(e => e.severity < 3);

    if (highSeverity.length > 0) {
      lines.push('### High Severity');
      for (const e of highSeverity.slice(0, 10)) {
        lines.push(`- **[${e.type}]** ${e.headline} *(${e.source}, severity ${e.severity}/5)*`);
      }
    }

    if (lowSeverity.length > 0) {
      lines.push('', '### Notable');
      for (const e of lowSeverity.slice(0, 5)) {
        lines.push(`- [${e.type}] ${e.headline} *(${e.source})*`);
      }
    }
  }

  // Track 2 performance
  lines.push('', '## Track 2: Volatility Capture Performance', '');
  if (track2Performance.total_trades === 0) {
    lines.push('*No trades yet. Paper trading not started.*');
  } else {
    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Total Trades | ${track2Performance.total_trades} |`);
    lines.push(`| Win Rate | ${(track2Performance.win_rate * 100).toFixed(1)}% |`);
    lines.push(`| Net P&L | $${track2Performance.net_pnl.toFixed(2)} |`);
    lines.push(`| Profit Factor | ${track2Performance.profit_factor.toFixed(2)} |`);
    lines.push(`| Sharpe Ratio | ${track2Performance.sharpe_ratio.toFixed(2)} |`);
    lines.push(`| Max Drawdown | ${(track2Performance.max_drawdown_pct * 100).toFixed(1)}% |`);
  }

  // Thesis status
  lines.push('', '## Active Theses', '');
  lines.push('| Thesis | Status | Key Metric to Watch |');
  lines.push('|--------|--------|---------------------|');
  lines.push('| Gold miner divergence | ACTIVE | GDX/GLD ratio |');
  lines.push('| Nuclear renaissance / HALEU | ACTIVE | Nuclear PPA announcements |');
  lines.push('| Copper supply deficit | ACTIVE | LME copper inventory |');
  lines.push('| Helium chokepoint | MONITORING | Ras Laffan reconstruction timeline |');
  lines.push('| Petrodollar erosion | MONITORING | Foreign central bank USD holdings |');
  lines.push('| Compute cost spiral | ACTIVE | DRAM/HBM spot prices |');

  lines.push('', '---', `*Generated by Macro Sentinel v0.1.0 at ${new Date().toISOString()}*`);

  return lines.join('\n');
}

async function main() {
  try {
    const briefing = await generateBriefing();
    const today = new Date().toISOString().split('T')[0];

    // Save to briefings directory
    const briefingDir = join(import.meta.dir, '..', 'data', 'briefings');
    mkdirSync(briefingDir, { recursive: true });
    writeFileSync(join(briefingDir, `${today}.md`), briefing);

    // Also save to egg briefing location for session start
    const eggDir = join(process.env.HOME ?? '~', '.claude', 'egg');
    mkdirSync(eggDir, { recursive: true });
    writeFileSync(join(eggDir, 'latest-briefing.md'), briefing);

    // Save to DB
    const db = getDb();
    db.run(
      'INSERT OR REPLACE INTO briefings (id, date, data, created_at) VALUES (?, ?, ?, ?)',
      [crypto.randomUUID(), today, briefing, new Date().toISOString()]
    );

    console.log(`[briefing] Saved to ${briefingDir}/${today}.md`);
    console.log(`[briefing] Updated egg briefing at ~/.claude/egg/latest-briefing.md`);
    console.log(briefing);
  } catch (err) {
    console.error('[briefing] Failed:', err);
    process.exit(1);
  }
}

main();
