name = "percival-website"
compatibility_date = "2024-12-01"
pages_build_output_dir = "out"

[[kv_namespaces]]
binding = "WAITLIST"
id = "e543441f515241b19df0ab35e1875a45"

[[kv_namespaces]]
binding = "SETUPS"
id = "c6ab3df4af2347bab8ecf2d9a3003299"
